# Python build file

universe = vanilla

executable = $(commands_file).sh
initial_dir = $(results_dir)
log = ../../$(log_dir)/$(Process).log
output = ../../$(log_dir)/$(Process).out
error = ../../$(log_dir)/$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_memory = 20GB
request_disk = 40GB

requirements = (Target.HasCHTCStaging == true)

queue 1